# Generated by Django 3.1.3 on 2020-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0004_loginslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='content_img',
        ),
        migrations.AddField(
            model_name='message',
            name='content_txt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoginsLog',
        ),
    ]
